name: my_to_do
description: "A simple to do list Flutter project with local storage."
publish_to: 'none'
version: 1.2.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  hive_flutter: ^1.1.0
  shared_preferences: ^2.5.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
